---
infrared_dir: "{{ ansible_user_dir }}/infrared"
infrared_workspaces_dir: "~/.infrared/.workspaces"
infrared_hosts_file: "{{ infrared_workspaces_dir }}/active/hosts"
instackenv_file: "{{ ansible_user_dir }}/instackenv.json"
cloud_name: cloud05
lab_name: alias
ansible_ssh_user: root
ansible_ssh_pass: 100yard-
ansible_ssh_key: "{{ ansible_user_dir }}/.ssh/id_rsa"
osp_release: 13
osp_puddle: passed_phase2
controller_count: 3
# No need to set compute_count. This will be set to all remaining nodes, which is calclulated in overcloud.yml
#compute_count: 1
alias:
#lab specific vars
  lab_url: "http://quads.alias.bos.scalelab.redhat.com"
scale:
# lab specific vars
  lab_url: "http://quads.rdu2.scalelab.redhat.com"
machine_types:
  supermicro:
    - 1029p
    - 1029u
    - 6048r
    - 5039ms
    - 6049p
    - 6048p
  dell:
    - r620
    - r630
    - r730xd
    - r930
    - 740xd
