---
# Obtain/Upload guest_images to OpenStack Cloud

- name: Fetch image centos7
  get_url:
    url: "{{ guest_images[item].url_centos7 }}"
    dest: "/home/stack/{{ guest_images[item].name }}.{{ guest_images[item].type }}"
  with_items: "{{ guest_images }}"
  when: ansible_distribution_major_version < '8'

- name: Fetch image centos8
  get_url:
    url: "{{ guest_images[item].url_centos8 }}"
    dest: "/home/stack/{{ guest_images[item].name }}.{{ guest_images[item].type }}"
  with_items: "{{ guest_images }}"
  when: ansible_distribution_major_version == '8'

- name: Determine if image exists
  shell: . {{ overcloudrc }}; openstack image list | grep '{{ guest_images[item].name }}'
  register: image_exists
  ignore_errors: true
  changed_when: false
  with_items: "{{ guest_images }}"

- name: Remove image from dictionary of images if image exists
  set_fact:
    guest_images: "{{ guest_images|dict_remove_item(item[0]) }}"
  when: item[0] in item[1].stdout and
        item[1] is defined
  with_nested:
    - "{{ guest_images }}"
    - "{{ image_exists.results }}"

- name: change the root password for qcow2 image
  shell: |
    export LIBGUESTFS_BACKEND=direct
    virt-customize -a {{user_dir }}/{{ guest_images[item].name }}.{{ guest_images[item].type }} --root-password password:"{{ vm_password }}"
  with_items: "{{ guest_images }}"

- name: Upload image into cloud 
  shell: . {{ overcloudrc }}; openstack image create --public --disk-format={{ guest_images[item].type }} --container-format=bare {{ guest_images[item].name }} < {{ user_dir }}/{{ guest_images[item].name }}.{{ guest_images[item].type }}
  ignore_errors: true
  with_items: "{{ guest_images }}"
