- hosts: localhost
  tasks:
      - name: remove {{ infrared_dir }}
        file:
            path: "{{ infrared_dir }}"
            state: absent
      - name: remove {{ ansible_user_dir }}/.infrared
        file:
            path: "{{ ansible_user_dir }}/.infrared"
            state: absent
      - name: remove {{ instackenv_file }}
        file:
            path: "{{ instackenv_file }}"
            state: absent
      - name: remove overcloud_instackenv.json
        file:
            path: "~/overcloud_instackenv.json"
            state: absent
      - name: remove nic-configs virt
        file:
            path: "{{ ansible_user_dir }}/virt"
            state: absent
      - name: remove nic-configs virt_4nics
        file:
            path: "{{ ansible_user_dir }}/virt_4nics"
            state: absent
      - name: Remove undercloud.conf
        file:
            path: "{{ ansible_user_dir }}/undercloud.conf"
            state: absent
      - name: Remove tn10rt.html
        file:
            path: "{{ ansible_user_dir }}/tn10rt.html"
            state: absent
