# Playbook to setup external networking and overcloud endpoint access on the undercloud

- hosts: undercloud
  gather_facts: yes
  vars:
       external_interface: "{{ hostvars['localhost']['external_interface'] }}"
  tasks:
      - name: set ext_iface
        set_fact:
          ext_iface: "{{ external_interface }}"
        when: virtual_uc != true

      - name: set ext_iface
        set_fact:
          ext_iface: "{{ vm_external_interface }}"
        when: virtual_uc == true

      - name: create vlan interface on external interface
        vars:
            vlan_interface: "{{ ext_iface }}.{{ external_network_vlan_id }}"
        shell: |
            ip link add link {{ ext_iface }} name {{ vlan_interface }} type vlan id {{ external_network_vlan_id }}
            ip link set dev {{ ext_iface }} up
            ip link set dev {{ vlan_interface }} up
            ip a a {{ external_gateway }} brd {{ external_network_broadcast }} dev {{ vlan_interface }}
        become: true
        ignore_errors: true

      - name: get default route
        shell: |
            ip r | grep default | cut -d ' ' -f5
        register: default_route
        become: true

      - name: masquerade on public interface
        shell: |
            iptables -t nat -A POSTROUTING -o {{ default_route.stdout }} -j MASQUERADE
        become: true

