---
- hosts: localhost
  tasks:
      - name: add undercloud_host to inventory file
        add_host:
            name: "{{ undercloud_hostname }}"
            ansible_user: "stack"
      - name: run tripleo-overcloud introspection
        shell: |
            source .venv/bin/activate
            infrared tripleo-overcloud -vvv --version {{ osp_release }} --build {{ osp_puddle }} --instackenv-file {{ undercloud_instackenv_path }} --deployment-files {{ nic_configs }} --introspect yes &> overcloud_introspect.log
        args:
            chdir: "{{ infrared_dir }}"
        changed_when: false
        ignore_errors: true

- hosts: undercloud
  tasks:
      - name: check and delete introspection failed nodes
        include_tasks: tasks/delete_introspection_failed_nodes.yml
