---
- hosts: undercloud
  gather_facts: yes
  tasks:
      # RHBZ 1756492
      - name: exclude ceph images
        lineinfile:
          path: /home/stack/containers-prepare-parameter.yaml
          insertafter: "- push_destination: true"
          line: '    excludes:'
        when: osp_release > 13
      - name: exclude ceph images
        lineinfile:
          path: /home/stack/containers-prepare-parameter.yaml
          insertafter: "    excludes:"
          line: '    - ceph'
        when: osp_release > 13
      - name: get tht version
        shell: |
          grep  "heat_template_version" /usr/share/openstack-tripleo-heat-templates/overcloud.j2.yaml | cut -d ':' -f2
        register: tht_version
      - name: set heat_template_version
        set_fact:
          heat_template_version: "{{ tht_version.stdout }}"

- hosts: localhost
  gather_facts: yes
  tasks:
      - name: Enable overcloud deployment with extra user defined templates
        block:
          - name: Check if the templates exist on the undercloud
            stat:
              path: "{{ item }}"
            register: env_files
            loop: "{{ extra_templates }}"
            delegate_to: "{{ undercloud_hostname }}"
            vars:
              ansible_python_interpreter: "{{ python_interpreter }}"
              ansible_user: "stack"

          - name: Copy files to undercloud if they do not exist
            copy:
              src: "{{ item.item }}"
              dest: "/home/stack/"
            loop: "{{ env_files.results }}"
            when: not item.stat.exists
            delegate_to: "{{ undercloud_hostname }}"
            vars:
              ansible_python_interpreter: "{{ python_interpreter }}"
              ansible_user: "stack"

          - name: Template out extra overcloud-templates file
            template:
              src: overcloud-templates.yml.j2
              dest: "{{ infrared_dir }}/plugins/tripleo-overcloud/vars/overcloud/templates/extra.yml"

          - name: load vars from extra.yml
            include_vars:
              file: "{{ infrared_dir }}/plugins/tripleo-overcloud/vars/overcloud/templates/extra.yml"

          - name: slurp heat templates content
            slurp:
              src: "{{ item }}"
            loop: "{{ tripleo_heat_templates }}"
            register: slurp_content
            delegate_to: "{{ undercloud_hostname }}"
            vars:
              ansible_python_interpreter: "{{ python_interpreter }}"
              ansible_user: "stack"

          - name: set vxlan fact
            set_fact:
              vxlan: true
            when: '"vxlan" in (item.content | b64decode )'
            with_items: "{{ slurp_content.results }}"

        when: ( extra_templates is defined and extra_templates|length>0 ) or ( parameter_defaults is defined and parameter_defaults|length>0 )
      - name: Set compute count fact
        set_fact:
            compute_count: "{{ compute_count|default(oc_instackenv_content.nodes|length - (controller_count|int)) }}"

      - name: get nodes
        shell: |
            source ~/stackrc
            openstack baremetal node list -f value -c UUID
        register: nodes_uuids
        changed_when: false
        delegate_to: "{{ groups.undercloud|first }}"
        vars:
          ansible_python_interpreter: "{{ python_interpreter }}"
          ansible_user: "stack"

      - name: check registered nodes with requested node count
        debug:
           msg: "Less nodes {{ nodes_uuids.stdout_lines|length }} registered with ironic than requested {{ compute_count|int + controller_count|int }}. So we will be adjusting controller and compute count according to registered available nodes"
        when: nodes_uuids.stdout_lines|length < (compute_count|int + controller_count|int)

      - name: Adjust compute count
        set_fact:
            compute_count: "{{ compute_count|int - 1 }}"
        when: nodes_uuids.stdout_lines|length < (compute_count|int + controller_count|int)
        with_items: "{{ nodes_uuids }}"

      - name: fail when compute count is less than 1
        fail:
            msg: "Failing as compute count is less than 1"
        when: compute_count|int < 1

      - name: check neutron_backend defined
        set_fact:
          neutron_backend: "{{ (osp_release|int > 14) | ternary('ovn', 'ovs') }}"
        when: neutron_backend is not defined

      - name: set ovn facts
        set_fact:
          network_backend: 'geneve'
          network_type: '--network-ovn'
        when: neutron_backend == 'ovn'

      - name: set ovs facts
        set_fact:
          network_backend: 'vxlan'
          network_type: '--network-ovs'
        when: neutron_backend == 'ovs'

      - name: run tripleo-overcloud deploy
        shell: |
            source .venv/bin/activate
            infrared tripleo-overcloud -vvv --version {{ osp_release }} --deployment-timeout 240 --deployment-files {{ nic_configs }} --introspect no --tagging no --deploy yes --controller-nodes {{ controller_count }} --compute-nodes {{ compute_count }} --network-protocol ipv4 --network-backend {{ network_backend }} {{ network_type }} true --public-network false > {{ log_directory }}/overcloud_deploy.log 2>&1
        args:
            chdir: "{{ infrared_dir }}"
        when: extra_templates is not defined and parameter_defaults is not defined

      - name: run tripleo-overcloud deploy with extra templates
        shell: |
            source .venv/bin/activate
            infrared tripleo-overcloud -vvv --version {{ osp_release }} --deployment-timeout 240 --build {{ osp_puddle }}  --deployment-files {{ nic_configs }} --introspect no --tagging no --deploy yes --controller-nodes {{ controller_count }} --compute-nodes {{ compute_count }} --overcloud-templates {{ infrared_dir }}/plugins/tripleo-overcloud/vars/overcloud/templates/extra.yml --network-protocol ipv4 --network-backend {{ network_backend }} {{ network_type }} true --public-network false > {{ log_directory }}/overcloud_deploy.log 2>&1
        args:
            chdir: "{{ infrared_dir }}"
        when: ( extra_templates is defined and extra_templates|length>0 ) or ( parameter_defaults is defined and parameter_defaults|length>0 )
