---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: installed
  loop:
      - git
      - gcc
      - libffi-devel
      - python-virtualenv
      - libselinux-python
      - python-netaddr
      - sshpass
      - ipmitool
      - python-pip
      - python3
      - python3-virtualenv
      - python3-libselinux
      - python3-netaddr
      - python3-pip
      - podman
  become: true
  failed_when: false

- block:
  - name: clone badfish
    git:
      repo: "https://github.com/redhat-performance/badfish.git"
      dest: "{{ ansible_user_dir }}/badfish"

  - name: set badfish venv path
    set_fact:
      badfish_venv: "{{ ansible_user_dir }}/badfish/.venv"

  - name: Create badfish virtualenv
    command: python3 -m venv {{ badfish_venv }} creates={{ badfish_venv }}

  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade
      virtualenv: "{{ badfish_venv }}"

  - name: Install badfish requirements
    pip:
      requirements: "{{ ansible_user_dir }}/badfish/requirements.txt"
      virtualenv_command: /usr/bin/python3 -m venv
      virtualenv: "{{ badfish_venv }}"
      
  - name: Install badfish packages
    shell: |
      source {{ badfish_venv }}/bin/activate;
      pip install -e .
    args:
      chdir: "{{ ansible_user_dir }}/badfish"
  when: virtual_uc == false or scale_compute_vms == true
